#!/bin/bash
# /etc/init.d/rCPU

### BEGIN INIT INFO
# Provides:          rCPU
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       The radioApi service is used to control radio streaming via HTTP
### END INIT INFO


case "$1" in 
    start)
        echo "Starting the radioApi service..."
        /usr/local/bin/radioApi/radioApi 8112 -d &
        echo "The radioApi service should be running"
        ;;
    stop)
        echo "Stopping the radioApi service..."
        killall -q radioApi &
        echo "The radioApi service should be stopped"
        ;;
    *)
        echo "Usage: /etc/init.d/radioApi start|stop"
        exit 1
        ;;
esac

exit 0